GET http://localhost:3000?name=John&age=20

###
POST http://localhost:3000
Content-Type: application/json

{
    "name": "John",
    "age": 20
}
###
PATCH http://localhost:3000
Content-Type: application/json

{
    "name": "John",
    "age": 20
}